### ISSUE TITLE
Chore: Add 8(a) in the Socioeconomic status filter

### ISSUE THREAD

**Issue by edeese8** [makegov/tango-public#13]
**Is your feature request related to a problem? Please describe.**
No. When user is searching for company profiles in the companies section. In the filter for Socioeconomic status a user could not find the filter for 8(a).

**Describe the solution you'd like**
The solution that is needed is adding the filter for 8(a) so users can search for this filter when searching for company profiles.

**Describe alternatives you've considered**
None.

**Additional context**
[loom](https://www.loom.com/share/d5314ee4b9814802abe6aa03e1b8a3bd?sid=bbffd249-3443-4a53-8dfb-4b16574cf553)

**Comment by vdavez** [comment]
@edeese8 Confirming... you mean 8(a)?

**Comment by edeese8** [comment]
@vdavez Yes I meant 8(a). Sorry for the confusion

**Comment by Danlobaton** [comment]
We already get this in /entities and `/bulk/entities`
