### ISSUE TITLE
Opportunity Search Capabilities

### ISSUE THREAD

**Issue by Danlobaton** [makegov/tango-public#4]
**Is your feature request related to a problem? Please describe.**
We have an excellent opportunity to enhance our users' ability to find relevant opportunities by introducing advanced, flexible search capabilities.

**Describe the solution you'd like**
Implement these powerful search features for the opportunities endpoint:

1. Keyword search:
   - Single query search across title and description fields for efficient exploration

2. Multiple NAICS codes search:
   - Enable searching by multiple NAICS codes (disjunctive) for broader industry coverage

3. Multiple PSC codes search:
   - Allow searching by multiple PSC codes (disjunctive) for comprehensive product/service discovery

4. Place of performance search (disjunctive):
   - Introduce flexible location-based searching by:
     - Country
     - State
     - City
     - Zip code
   - Enable intuitive queries like "all opportunities in the US", "Opportunities in Washington state", etc.

**Describe alternatives you've considered**
While separate filter parameters could work, an integrated search approach will provide a more intuitive and powerful querying experience for our users.

**Additional context**
These advanced search features will significantly enhance our users' ability to discover relevant opportunities, making our API an even more valuable tool for opportunity exploration and business growth.

**Comment by infinityplusone** [comment]
@Danlobaton This has been released in v1.4.0. The only thing that isn't there is this:
> Enable intuitive queries like "all opportunities in the US", "Opportunities in Washington state", etc.
